{extends 'file:templates/EmptyTemplate.tpl'}
{block 'main'}
    {include 'file:chunks/intro/_main_intro.tpl'}
    {include 'file:chunks/blocks/block002_UK_advantage.tpl'}
    {include 'file:chunks/blocks/block003_nature_factor.tpl'}
    {include 'file:chunks/blocks/block004_video_wide.tpl'}
    {include 'file:chunks/blocks/block005_med_profile_list.tpl'}
    {include 'file:chunks/blocks/block006_list_sanatorium.tpl'}
    {include 'file:chunks/blocks/block007_calc.tpl'}
    {include 'file:chunks/blocks/block008_news_slider.tpl'}
    {include 'file:chunks/blocks/block010_1_mineral_water.tpl'}
    {include 'file:chunks/blocks/block010_2_Healing_clay.tpl'}
    {include 'file:chunks/blocks/block012_gallery_wide.tpl'}
    {include 'file:chunks/blocks/block010_3_Salt_brines.tpl'}
    {include 'file:chunks/blocks/block_weather.tpl'}
    {include 'file:chunks/blocks/block015_entertainment.tpl'}
    {include 'file:chunks/blocks/block006_list_camping.tpl'}
    {include 'file:chunks/main_page/_healthy_children.tpl'}
    {include 'file:chunks/blocks/block017_reviews.tpl'}
    {include 'file:chunks/blocks/block013_bottom_help.tpl'}
{/block}
